version: '3'
services:
  rabbitmq:
    build: rabbitmq/
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
    ports:

      - 5672:5672
      - 15672:15672

  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'digipay'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'

  paymentservice:
    build: paymentservice/
    ports:
      - "8080:8080"
  notificationservice:
    build: notificationservice/
    ports:
      - "8090:8090"


